### ISSUE TITLE
DigiKey BOM for North American Part Numbers

### ISSUE THREAD

**Issue by ChrisToast89** [svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness#2]
Sourcing assistance part numbers from N. American vendor(s).

[Diag Harness BOM (N.American DIGIKEY PNs).xlsx](https://github.com/svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness/files/3221005/Diag.Harness.BOM.N.American.DIGIKEY.PNs.xlsx)

**Comment by ChrisToast89** [comment]
Note for Sven: I ended up sourcing SMT LED and caps out of preference since the pad layouts allowed me the option. However, traditional through-hole resistors were used.

**Comment by svenpetersen1965** [comment]
I will add your file to the repository.
