### ISSUE TITLE
Paddle test indicates false failure on some boards 

### ISSUE THREAD

**Issue by dgoswick** [svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness#3]
I ran into a board that kept failing the paddle test and insisted that either the SID or U28 (4066) was bad.  The SID was known good, and tested fine in another board.  I replaced U28, but the problem persisted.  Reading through the original diagnostic cartridge manual, I noticed that Commodore used 110k resistors to pull the 4 POT lines up to +5v.  The diagnostic harness here uses 120k resistors (R1,R2,R5,R6) on the user port to achieve the same.  On a hunch, I changed these resistors on the user port of the harness to 110k.  The diagnostic test is now passing every time without fail for this board.

Thank you Sven for all of your contributions to the retro community!
Dan Goswick

**Comment by svenpetersen1965** [comment]
Thanks for the hint. I will take care of that soon.

**Comment by svenpetersen1965** [comment]
Done.
