### ISSUE TITLE
LED is always on on Extended Keyboard Dongle

### ISSUE THREAD

**Issue by nharrer** [svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness#6]
First off. This is a wonderful project. Thank you so much! I had so much fun building it and testing my growing fleet of C64s and 128s.
I also tried the extended Keyboard version with the single wire connection to the cassette board.

Here I noticed that the LED is always on, even when J2 is disconnected. I have placed R5 and removed R3. So it should be off if the jumper is disconnected.

It seems that R1 is too low. Even with the control line (IC1B Pin 4) pulled to low, there is enough current to turn on Q1. I have tried different values for R2 and R4. And I found that it works well if the resistances are raised by a magnitude. R2 = 10k and R4 = 47k. This gives the same well defined ctrl voltage for the high state (about 4,1V) but not enough current to turn on Q1 on the low state.

Here is a list of values that I've tried for R2 / R4 (also attached):
![Ext_Keyboard_LED_fault](https://user-images.githubusercontent.com/8344095/149667045-7cf9bce9-1b16-4722-8a59-5e21ac66f209.png)
_U<sub>J2</sub> is the voltage on Pin 5 of IC1B (the signal from J2)
U<sub>A</sub> is the voltage in Pin 4 of IC1B
U<sub>Q</sub> is the voltage on the base if Q1_

You mentioned in your docs that you started out with R2 = 10k and it didn’t work. I noticed the same thing when R4 = 0. But it works well, if R4 is high enough (at the same ration of R2 / R4 as the current version).

I hope this makes sense. Disclaimer: Electronics is just a hobby of mine. I could be completely on the wrong track.
Regards,
Norbert

[Ext_Keyboard_LED_fault.ods](https://github.com/svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness/files/7877303/Ext_Keyboard_LED_fault.ods)

**Comment by svenpetersen1965** [comment]
IC1B is used as an inverter. A High in one Ctrl-Input will switch the "output" Pin 4 to GND on Pin 5. If the on-Resistance of the 4066 is too high, the voltage on Pin4 will not get low enough to switch off the feedbacks and the LED.  My mistake in Rev. 0 was connecting the ctrl input directly to the base of the transistor. The voltage could not get higher tan about 0.7V, which is still low. the ctrl needs to be 3.5V for a valid high signal.
 
The on resistance is typically 125 Ohm (I just read, that is for 15V supply voltage is can be 470ohms). And the valid LOW level is  1V. Hmm... so my dongle works, but the values are a bit delicate. Which IC brand did you install?

I have played a bit with the values. R2 should be good with 3k3 and R4 with 10k. Are you able to check these values? I cannot find my prototype right now.

**Comment by nharrer** [comment]
Thanks for the explanation. I didn't realize that R<sub>on</sub> of the 4066 is quite high.

I have no idea what brand I have. Probably bought on Aliexpress:
![image](https://user-images.githubusercontent.com/8344095/149985088-64ec271c-258a-4073-9ddd-004f45af634f.png)

I measured I<sub>A</sub> and V<sub>A</sub> at Pin 4 when IC1B is on. Which is 1.32mA and 0.7V. That results in about 260Ω. Which is quite higher than 125.

And I tried the values R2=3k3 and R4=10k. That works! That ctrl signal high state is 3.8V in that case.
I stuck it onto three different C64s and it looks good so far.

**Comment by svenpetersen1965** [comment]
Good, that it works, now. Issue closed.
