### ISSUE TITLE
Harness Rev.3 THT R3 Value

### ISSUE THREAD

**Issue by venice1200** [svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness#8]
Hi,
das hier ist kein Issue, mehr ein Hinweis zu R3 in der Rev. 3.0 THT Variante.

Ich baue mir gerade Dein Harness in der o.g. Rev. auf und habe bemerkt 
das in der Rev. 3.0 Doku und auf dem PCB verschiedene Werte angegeben sind.

Gefunden habe ich:
- Auf dem PCB Rev. 3.0 steht 316R
- In der Projekt Doku werden an mehreren Stellen 330R angegeben (Motor Signal, Bestückung)
- Im "Bill of Material Rev. 3.0" sind wider  316R gelistet

Ich denke der Unterschied zwischen 316 und 330 Ohm ist vernachlässigbar, 
vielleicht kannst Du das aber noch in die Doku mit aufnehmen.

Danke das Du das hier alles frei zur Verfügung stellst.

Viele Grüße
Lars

P.S. Das "Issue" kannst Du gerne gleich wieder schliessen.

**Comment by svenpetersen1965** [comment]
Original war da 316Ω drin. Aber 330Ω funktionieren genau so. Da ich einen 330Ω als Vorwiderstand für die LED habe, und das einfacher zu bekommen ist, habe ich es auf 330Ω umgestellt. Aber du kannst beide Werte an beiden Stellen verwenden. Ich muss mir die Doku noch einmal ansehen. Danke für den Hinweis.
Sven

**Comment by svenpetersen1965** [comment]
I have found an obsolete BOM in the pdf. The Excel BOM v3.0 was up to date. The top silk screen also contained the old value. This is now fixed.
