### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Obiwantje** [svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness#9]
"Now, a 3D printed case for the user port and the cassette donge is designed and the stl files etc. are available here.

Diagnostic Harness with cases"

Link in readme to: [https://github.com/svenpetersen1965/C64-Diagnostic-Rev.-586220-Harness/blob/master/Diag586220_Harness/Case%20(3D%20print)/Rev.%200/Picture/2649_Harness_with_case.JPG]
is dead

**Comment by svenpetersen1965** [comment]
Thanks for the hint, I have fixed it.
